### PR TITLE
Migrate to .Net Standard 2.0

### LINKED ISSUE #3: .Net Standard version
This utility works great. 
Any plans to release a .Net Standard version of this?
OR
if we would like to do the port ourselves, do you foresee any compatibility issues

### PR DESCRIPTION
**Pull request by Thoorium**
Migrated the projects to .Net Standard 2.0. I've picked 2.0 for a wider support with the .Net ecosystem.

Resolves #3

### CODE REVIEW

**Comment by mwilliamson** [comment]
I haven't worked with .NET for a while, so I might have to do some reading around before taking a look at this. Having said that, it looks like the Travis build is failing.

**Comment by Thoorium** [comment]
For the Travis build, I have to edit the travis file to let it build using .Net Core instead of Mono and maybe a few other things. It failed because the format of the csproj files has changed. I'll get to it maybe this weekend.

**Comment by moetelo** [comment]
@mwilliamson @Thoorium any updates on this?

**Comment by manzanotti** [comment]
@mwilliamson Is there anything that you need doing to this PR before it gets merged? I'm using the NuGet package in a .Net 6 project, and whilst it seems to work fine, it does give me build warnings because it targets the Asp.Net Framework.

**Comment by mwilliamson** [comment]
Sorry for never taking a proper look at this. The `master` branch should now targets .NET Standard 2.0.

**Pull request closed without merging**
